name = "TSPDrone"
uuid = "ec3913bb-036d-4a1d-a51c-80e93297dcf2"
authors = ["Changhyun Kwon <chkwon@gmail.com> and contributors"]
version = "0.1.0"

[deps]
Concorde = "df6a336b-a67f-4155-81fc-4f05fe893652"
Match = "7eb4fadd-790c-5f42-8a69-bfa0b872bfbf"
PyCall = "438e738f-606a-5dbb-bf0a-cddfbfd45ab0"
Statistics = "10745b16-79ce-11e8-11f9-7d13ad32a3b2"

[compat]
PyCall = "1.90"
Match = "1.2"
Concorde = "0.1, 0.2"
julia = "1"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
